name: Gitbook Generation

on:
  push:
    branches:
      - "main"
      - "gitbook-generation"

jobs:
  gitbook-generation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        book: [Home, Getting-Started-with-InnerSource, Understanding-the-InnerSource-Checklist]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ matrix.book }}
    - name: Merge branch into branch for the book
      uses: mtanzi/action-automerge@v1
      with:
        github_token: ${{ github.token }}
        source: 'main'
        target: ${{ matrix.book }}
    - name: Copy .gitbook.yml to root
      run: cp ${{ matrix.book }}/.gitbook.yaml .
    - name: Commit updated files for the book
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Writing updated files for the book
        branch: ${{ matrix.book }}
