name: Markdownlint for Dev
# Including Understaning-the-InnerSource-Checklist/ in the markdownlint run
on:
  push:
    branches:
      - "utic-*"
    paths:
      - "**/*.md"
      - ".markdownlint.json"
      - ".github/workflows/markdownlint.yml"
      - ".github/workflows/markdownlint-problem-matcher.json"
  pull_request:
    branches:
      - "utic-*"
    paths:
      - "**/*.md"
      - ".markdownlint.json"
      - ".github/workflows/markdownlint.yml"
      - ".github/workflows/markdownlint-problem-matcher.json"

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run Markdownlint
      run: |
        echo "::add-matcher::.github/workflows/markdownlint-problem-matcher.json"
        npm i -g markdownlint-cli
        markdownlint "**/*.md"