name: TextLint

on:
  push:
    path:
      - '**.md'
  pull_request:
    path:
      - '**.md'
jobs:
  run-textlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Run TextLint
      run: |
        npm install -g textlint textlint-rule-prh textlint-filter-rule-allowlist textlint-rule-preset-ja-technical-writing textlint-rule-helper
        textlint -c ./textlint/.textlintrc ./Getting-Started-with-InnerSource/jp.md