name: TextLint

on:
  push:
    path:
      - '**.md'
  pull_request:
    path:
      - '**.md'
jobs:
  run-textlint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    # - name: Cache Dependencies
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.npm
    #     key: npm-${{ hashFiles('package-lock.json') }}
    #     restore-keys: npm-
    # - name: Install TextLint
    #   run: npm install --save-dev textlint textlint-rule-prh textlint-filter-rule-allowlist textlint-rule-preset-ja-technical-writing 
        
    - name: Install Dependent Module
      run: npm install

    - name: Run TextLint
      run: npm run textlint "**/jp.md"